### PR TITLE
Update dependency com.google.devtools.ksp to v2

### PR DESCRIPTION
**Pull request by tmapes**
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [com.google.devtools.ksp](https://goo.gle/ksp) ([source](https://togithub.com/google/ksp)) | plugin | major | `1.9.24-1.0.20` -> `2.0.0-1.0.22` |

---

### Release Notes

<details>
<summary>google/ksp (com.google.devtools.ksp)</summary>

### [`v2.0.0-1.0.22`](https://togithub.com/google/ksp/releases/tag/2.0.0-1.0.22)

[Compare Source](https://togithub.com/google/ksp/compare/2.0.0-1.0.21...2.0.0-1.0.22)

#### Important Changes

-   `KSErrorType.toString()` now contains the reference name it was tried to be resolved, and therefore `KSErrorType` is no longer a singleton. Processors relying on equality checks of that (in contrast of using `KSType.isError`) will need to be updated accordingly.

#### Issues Fixed

[#&#8203;1908](https://togithub.com/google/ksp/issues/1908) KSP2: Calling KSP2 in programs does not appear to work on macOS or Windows
[#&#8203;1917](https://togithub.com/google/ksp/issues/1917) KSP2's symbol-processing-aa-embeddable artifact exposes an unresolvable pre-release kotlin 2.0.20 dependency
[#&#8203;1911](https://togithub.com/google/ksp/issues/1911) NoSuchMethodError when running KSP2 with Dagger (KSP 2.0.0-1.0.21)
[#&#8203;1909](https://togithub.com/google/ksp/issues/1909) KSP2: default annotation arguments no longer work in 1.0.21
[#&#8203;1232](https://togithub.com/google/ksp/issues/1232) Expose simple names on a missing types's synthetic declaration
[#&#8203;1857](https://togithub.com/google/ksp/issues/1857) \[KSP2] Modifiers are missing for property accessors
[#&#8203;1924](https://togithub.com/google/ksp/issues/1924) \[KSP2] Type arg becomes '\*' after calling KSType.replace() with an error type
[#&#8203;1948](https://togithub.com/google/ksp/issues/1948) KSP2 default annotation KClass values for built-in types use java.lang.\* versions

#### What's Changed

-   Include type hint into KSErrorType. by [@&#8203;Jeffset](https://togithub.com/Jeffset) in [https://github.com/google/ksp/pull/1848](https://togithub.com/google/ksp/pull/1848)
-   Implement Resolver.getModuleName API by [@&#8203;ZacSweers](https://togithub.com/ZacSweers) in [https://github.com/google/ksp/pull/1847](https://togithub.com/google/ksp/pull/1847)
-   Patch AA service files in renamed uber jar by [@&#8203;ting-yuan](https://togithub.com/ting-yuan) in [https://github.com/google/ksp/pull/1867](https://togithub.com/google/ksp/pull/1867)
-   fix annotation default value parsing for arrays and class literals. by [@&#8203;neetopia](https://togithub.com/neetopia) in [https://github.com/google/ksp/pull/1871](https://togithub.com/google/ksp/pull/1871)
-   fix package name for library based symbols by [@&#8203;neetopia](https://togithub.com/neetopia) in [https://github.com/google/ksp/pull/1873](https://togithub.com/google/ksp/pull/1873)
-   Do not index classpath in declaration provider by [@&#8203;ting-yuan](https://togithub.com/ting-yuan) in [https://github.com/google/ksp/pull/1870](https://togithub.com/google/ksp/pull/1870)
-   check functional interface for modifiers by [@&#8203;neetopia](https://togithub.com/neetopia) in [https://github.com/google/ksp/pull/1872](https://togithub.com/google/ksp/pull/1872)
-   Annotation default java by [@&#8203;neetopia](https://togithub.com/neetopia) in [https://github.com/google/ksp/pull/1879](https://togithub.com/google/ksp/pull/1879)
-   fix type parameter bounds by [@&#8203;neetopia](https://togithub.com/neetopia) in [https://github.com/google/ksp/pull/1880](https://togithub.com/google/ksp/pull/1880)
-   Add command line parser and entry points by [@&#8203;ting-yuan](https://togithub.com/ting-yuan) in [https://github.com/google/ksp/pull/1885](https://togithub.com/google/ksp/pull/1885)
-   KSP2: Fix support of wasm by [@&#8203;ting-yuan](https://togithub.com/ting-yuan) in [https://github.com/google/ksp/pull/1888](https://togithub.com/google/ksp/pull/1888)
-   Return KSClassDeclarationEnumEntryImpl for enum entry annotation values. by [@&#8203;neetopia](https://togithub.com/neetopia) in [https://github.com/google/ksp/pull/1881](https://togithub.com/google/ksp/pull/1881)
-   Reuse Kotlin indexes in incremental providers by [@&#8203;ting-yuan](https://togithub.com/ting-yuan) in [https://github.com/google/ksp/pull/1891](https://togithub.com/google/ksp/pull/1891)
-   special handling for java property accessors override checking by [@&#8203;neetopia](https://togithub.com/neetopia) in [https://github.com/google/ksp/pull/1894](https://togithub.com/google/ksp/pull/1894)
-   KSP2: Reuse Java indexes by [@&#8203;ting-yuan](https://togithub.com/ting-yuan) in [https://github.com/google/ksp/pull/1895](https://togithub.com/google/ksp/pull/1895)
-   Incremental: fix roots from getSealedSubclasses  by [@&#8203;ting-yuan](https://togithub.com/ting-yuan) in [https://github.com/google/ksp/pull/1893](https://togithub.com/google/ksp/pull/1893)
-   use safe cast for annotation type to declaration resolution by [@&#8203;neetopia](https://togithub.com/neetopia) in [https://github.com/google/ksp/pull/1902](https://togithub.com/google/ksp/pull/1902)

**Full Changelog**: https://github.com/google/ksp/compare/2.0.0-1.0.21...2.0.0-1.0.22

### [`v2.0.0-1.0.21`](https://togithub.com/google/ksp/releases/tag/2.0.0-1.0.21)

[Compare Source](https://togithub.com/google/ksp/compare/1.9.24-1.0.20...2.0.0-1.0.21)

This release brings mostly bug fixes into [KSP2 beta](https://togithub.com/google/ksp/blob/main/docs/ksp2.md)
Users are encouraged to try out KSP2 beta.

##### new feature

expose an API in Resolver to retrieve the module name for handling mangling of internal members [#&#8203;1621](https://togithub.com/google/ksp/issues/1621)

##### issues fixed

-   Class values are missing class type in annotation values [#&#8203;1646](https://togithub.com/google/ksp/issues/1646)
-   Kotlin Function\* types reports inconsistent package and qualified names [#&#8203;1845](https://togithub.com/google/ksp/issues/1845)
-   KSP2 cannot load Android lint checks jar due to FileTooBigException [#&#8203;1839](https://togithub.com/google/ksp/issues/1839)
-   \[KSP2] KSAnnotations with annotation properties with a default value always resolve to null [#&#8203;1843](https://togithub.com/google/ksp/issues/1843)
-   \[KSP2] Modifier.FUN is missing in functional interfaces [#&#8203;1853](https://togithub.com/google/ksp/issues/1853)
-   \[KSP2] ClassCastException when calling KSType.starProjection() on a Java field type [#&#8203;1735](https://togithub.com/google/ksp/issues/1735)
-   \[KSP2] Annotation arguments with default values are missing [#&#8203;1837](https://togithub.com/google/ksp/issues/1837)
-   \[KSP2] Intersection types are not modeled [#&#8203;1846](https://togithub.com/google/ksp/issues/1846)
-   KSP2: Model enum entries in annotation values [#&#8203;1861](https://togithub.com/google/ksp/issues/1861)
-   KSP2: Unknown JS backend: Wasm [#&#8203;1889](https://togithub.com/google/ksp/issues/1889)
-   \[KSP2] NullPointerException when getting arguments of annotation value [#&#8203;1798](https://togithub.com/google/ksp/issues/1798)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).

### CODE REVIEW

**Comment by tmapes** [comment]
### Renovate Ignore Notification

Because you closed this PR without merging, Renovate will ignore this update. You will not get PRs for *any* future `2.x` releases. But if you manually upgrade to `2.x` then Renovate will re-enable `minor` and `patch` updates automatically.

If you accidentally closed this PR, or if you changed your mind: rename this PR to get a fresh replacement PR.
